version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./data:/data
    environment:
      - FLASK_APP=app/main.py
      - FLASK_ENV=development
      - CHROMA_SERVER_HOST=chromadb
      - CHROMA_SERVER_PORT=8000
    depends_on:
      - chromadb
    networks:
      - docker-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    networks:
      - docker-network
    deploy:
      resources:
        limits:
          memory: 512M  # Increase memory limit as needed
        reservations:
          memory: 256M  # Reserve memory as needed

  chromadb:
    build: 
      context: .
      dockerfile: Dockerfile.chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./data/chromadb:/chromadb/data
    networks:
      - docker-network

networks:
  docker-network:
    name: docker-network